services:
  mailing:
    image: mailhog/mailhog:latest
    volumes:
      - maildir_volume:/home/mailhog/user_config
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailing.rule=Host(`mailing.${DOMAIN}`)
      - traefik.http.services.mailing.loadbalancer.server.port=8025

volumes:
  maildir_volume: