name: "Static Analysis"

on: [ push, pull_request ]

jobs:
  analyse:
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.3" ]
        laravel: [ "^10.0"]
    name: "P${{ matrix.php }} - L${{ matrix.laravel }}"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: "actions/checkout@v3"

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "gd, intl, fileinfo"
          tools: "composer:v2"
          coverage: "none"

      - name: Install dependencies
        run: "composer install --ignore-platform-reqs"
        working-directory: platform

      - name: Validate composer
        run: "composer validate --strict"
        working-directory: platform

      - name: Up Laravel Application
        run: |
          cd platform/
          cp .env.example .env
          php artisan key:generate

      - name: Require Laravel Pint
        run: "composer require laravel/pint --dev --no-update --no-interaction --no-progress"
        working-directory: platform

      - name: Require Laravel Stan
        run: "composer require larastan/larastan:^2.0 --dev --no-update --no-interaction --no-progress"
        working-directory: platform

      - name: Execute linter analysis
        run: "composer run-script pint"
        working-directory: platform

      - name: Execute static analysis
        run: "composer run-script stan"
        working-directory: platform
